name: Build
run-name: ${{ github.actor }} is building library package
on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/setup

      - name: Build
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/setup

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/setup

      - name: Test
        run: pnpm test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
